name: premerge
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  premerge:
    name: premerge
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: yarn install
      - name: typescript
        run: yarn tsc --noEmit
      - name: lint
        run: yarn lint
      - name: format
        run: yarn prettier . --check
